# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.95

map f11 toggle_fullscreen

font_family FiraCode Nerd Font
font_size 12

shell /bin/zsh

cursor_shape block
shell_integration no-cursor
enable_audio_bell no

hide_window_decorations yes
