" These are generated by ChatGPT
command! Cmake      call CMakeConfigure()
command! Cmakebuild call CMakeBuild()

function! s:open_outbuf(title) abort
  botright split
  resize 15
  enew
  setlocal buftype=nofile bufhidden=wipe noswapfile
  setlocal nowrap nonumber norelativenumber signcolumn=no
  execute 'file ' .. a:title
endfunction

function! s:append(ch, msg) abort
  if empty(a:msg) | return | endif
  call append('$', a:msg)
  normal! G
endfunction

function! CMakeConfigure() abort
  call s:open_outbuf('[CMake Configure]')
  call job_start(['cmake', '-S.', '-Bbuild'], {
        \ 'out_cb': function('s:append'),
        \ 'err_cb': function('s:append'),
        \ })
endfunction

function! CMakeBuild() abort
  call s:open_outbuf('[CMake Build]')
  call job_start(['cmake', '--build', 'build'], {
        \ 'out_cb': function('s:append'),
        \ 'err_cb': function('s:append'),
        \ })
endfunction
