" Ensure our syntax files (e.g. syntax/cpp.vim) are used first
" set rtp^=~/.vim

source ~/.vim/options.vim
source ~/.vim/keymaps.vim
source ~/.vim/plugins.vim
source ~/.vim/colorscheme.vim
source ~/.vim/undo-tree.vim
source ~/.vim/lsp.vim
source ~/.vim/packadd.vim
source ~/.vim/custom.vim
